/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    markets: Market;
    destinations: Destination;
    'travel-programs': TravelProgram;
    events: Event;
    services: Service;
    offers: Offer;
    guides: Guide;
    testimonials: Testimonial;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    'travel-programs': TravelProgramsSelect<false> | TravelProgramsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: 'admin' | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the meaningful subject of the image.
   */
  alt: string;
  /**
   * Optional photographer/source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: number;
  name: string;
  code: string;
  locale: string;
  currency: {
    code: string;
    symbol: string;
  };
  isDefault?: boolean | null;
  isActive?: boolean | null;
  isPublic?: boolean | null;
  contact?: {
    office?: string | null;
    reservationsEmail?: string | null;
    salesEmail?: string | null;
    whatsapp?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Keep it stable after publication.
   */
  slug: string;
  country: string;
  regionOrCity?: string | null;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Optional remote demo image URL. Prefer a Media upload for production content.
   */
  imageUrl?: string | null;
  gallery?: (number | Media)[] | null;
  featured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Only markets selected here may show this record publicly.
   */
  markets: (number | Market)[];
  relatedPrograms?: (number | TravelProgram)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-programs".
 */
export interface TravelProgram {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Keep it stable after publication.
   */
  slug: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  destinations: (number | Destination)[];
  coverImage?: (number | null) | Media;
  /**
   * Optional remote demo image URL. Prefer a Media upload for production content.
   */
  imageUrl?: string | null;
  gallery?: (number | Media)[] | null;
  durationDays: number;
  startingPrice: {
    amount: number;
    currency: string;
    unit?: ('person' | 'group' | 'night') | null;
  };
  itinerary?:
    | {
        day: number;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  notIncluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  accommodation?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Only markets selected here may show this record publicly.
   */
  markets: (number | Market)[];
  offer?: (number | null) | Offer;
  whatsappMessageOverride?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Keep it stable after publication.
   */
  slug: string;
  badge?: string | null;
  headline: string;
  description: string;
  discountLabel?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional remote demo image URL. Prefer a Media upload for production content.
   */
  imageUrl?: string | null;
  ctaLabel?: string | null;
  program?: (number | null) | TravelProgram;
  status: 'draft' | 'published' | 'archived';
  /**
   * Only markets selected here may show this record publicly.
   */
  markets: (number | Market)[];
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Keep it stable after publication.
   */
  slug: string;
  location: string;
  destination?: (number | null) | Destination;
  startDate: string;
  endDate?: string | null;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Optional remote demo image URL. Prefer a Media upload for production content.
   */
  imageUrl?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Only markets selected here may show this record publicly.
   */
  markets: (number | Market)[];
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Keep it stable after publication.
   */
  slug: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Stable presentation key, not raw SVG markup.
   */
  iconKey?: string | null;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Only markets selected here may show this record publicly.
   */
  markets: (number | Market)[];
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * Lowercase URL segment. Keep it stable after publication.
   */
  slug: string;
  summary: string;
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('Destination guide' | 'Travel tips' | 'Inspiration' | 'Planning') | null;
  coverImage?: (number | null) | Media;
  /**
   * Optional remote demo image URL. Prefer a Media upload for production content.
   */
  imageUrl?: string | null;
  relatedDestinations?: (number | Destination)[] | null;
  publishedAt?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Only markets selected here may show this record publicly.
   */
  markets: (number | Market)[];
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  displayName: string;
  location?: string | null;
  quote: string;
  avatar?: (number | null) | Media;
  rating?: number | null;
  featured?: boolean | null;
  /**
   * Keep enabled for seed/demo reviews until replaced with supplied customer content.
   */
  isDemoContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: string | null;
  order: number;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'travel-programs';
        value: number | TravelProgram;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  locale?: T;
  currency?:
    | T
    | {
        code?: T;
        symbol?: T;
      };
  isDefault?: T;
  isActive?: T;
  isPublic?: T;
  contact?:
    | T
    | {
        office?: T;
        reservationsEmail?: T;
        salesEmail?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  country?: T;
  regionOrCity?: T;
  summary?: T;
  content?: T;
  coverImage?: T;
  imageUrl?: T;
  gallery?: T;
  featured?: T;
  status?: T;
  markets?: T;
  relatedPrograms?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-programs_select".
 */
export interface TravelProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  destinations?: T;
  coverImage?: T;
  imageUrl?: T;
  gallery?: T;
  durationDays?: T;
  startingPrice?:
    | T
    | {
        amount?: T;
        currency?: T;
        unit?: T;
      };
  itinerary?:
    | T
    | {
        day?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  accommodation?: T;
  featured?: T;
  status?: T;
  markets?: T;
  offer?: T;
  whatsappMessageOverride?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  destination?: T;
  startDate?: T;
  endDate?: T;
  summary?: T;
  content?: T;
  coverImage?: T;
  imageUrl?: T;
  featured?: T;
  status?: T;
  markets?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  iconKey?: T;
  coverImage?: T;
  featured?: T;
  status?: T;
  markets?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badge?: T;
  headline?: T;
  description?: T;
  discountLabel?: T;
  startsAt?: T;
  endsAt?: T;
  image?: T;
  imageUrl?: T;
  ctaLabel?: T;
  program?: T;
  status?: T;
  markets?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  coverImage?: T;
  imageUrl?: T;
  relatedDestinations?: T;
  publishedAt?: T;
  featured?: T;
  status?: T;
  markets?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  displayName?: T;
  location?: T;
  quote?: T;
  avatar?: T;
  rating?: T;
  featured?: T;
  isDemoContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  defaultMarket: number | Market;
  canonicalUrl?: string | null;
  contact: {
    whatsappDisplay: string;
    whatsappNumber: string;
    office: string;
    reservationsEmail: string;
    salesEmail: string;
  };
  whatsapp?: {
    defaultMessage?: string | null;
    contextTemplate?: string | null;
  };
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerCopy?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (number | null) | Media;
    canonicalUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    eyebrow: string;
    headline: string;
    supportingCopy: string;
    image?: (number | null) | Media;
    /**
     * Optional remote demo image URL. Prefer a Media upload for production content.
     */
    imageUrl?: string | null;
    primaryCta: {
      label: string;
      kind: 'whatsapp' | 'internal' | 'external';
      url?: string | null;
    };
    secondaryCta: {
      label: string;
      kind: 'whatsapp' | 'internal' | 'external';
      url?: string | null;
    };
  };
  featuredDestinations?: (number | Destination)[] | null;
  popularPrograms?: (number | TravelProgram)[] | null;
  activeOffer?: (number | null) | Offer;
  upcomingEvents?: (number | Event)[] | null;
  featuredTestimonials?: (number | Testimonial)[] | null;
  latestGuides?: (number | Guide)[] | null;
  faqs?: (number | Faq)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  defaultMarket?: T;
  canonicalUrl?: T;
  contact?:
    | T
    | {
        whatsappDisplay?: T;
        whatsappNumber?: T;
        office?: T;
        reservationsEmail?: T;
        salesEmail?: T;
      };
  whatsapp?:
    | T
    | {
        defaultMessage?: T;
        contextTemplate?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerCopy?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        supportingCopy?: T;
        image?: T;
        imageUrl?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              kind?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              kind?: T;
              url?: T;
            };
      };
  featuredDestinations?: T;
  popularPrograms?: T;
  activeOffer?: T;
  upcomingEvents?: T;
  featuredTestimonials?: T;
  latestGuides?: T;
  faqs?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}